# Site settings
title:        George Yu
SEOTitle:     Blog | George Yu
header-img:   img/home-bg.jpg
email:        george@georgeyu.cn
description:  'This is a blog of George Yu.'
keyword:      ''
url:          'http://blog.georgeyu.cn'
baseurl:      ''


# SNS settings
RSS:                  false
github_username:      yu-george
zhihu_username:       于佳铭
# weibo_username:     huxpro
# twitter_username:   huxpro
# facebook_username:  huxpro


# Build settings
highlighter:  rouge
permalink:    pretty
paginate:     10 # articles in one page
exclude:      ['less', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'README.zh.md', 'CNAME']
anchorjs:     true


# Gems
plugins: [jekyll-paginate]


# Markdown settings
# Kramdown documentation: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important


# Disqus settings
# disqus_username: _your_disqus_short_name_


# Duoshuo settings
# duoshuo_username:  huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share:     false # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id:  4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id:    'UA-108824572-1'
ga_domain:      georgeyu.cn


# Sidebar settings
sidebar:                    true
sidebar-about-description:  'High school student based in Shanghai, China. Enthusiast in computer science and mathematics.'
sidebar-avatar:             /img/avatar.jpg # use absolute URL


# Featured Tags
featured-tags:            true
featured-condition-size:  1 # a tag will be featured if the size of it is more than this threashold


# Friends
# friends: [
#     {
#         title: 'Hux Blog',
#         href: 'http://huangxuan.me'
#     },{
#         title: 'Foo',
#         href: '#'
#     },{
#         title: 'Bar',
#         href: '#'
#     },{
#         title: 'Example Friends',
#         href: '#'
#     },{
#         title: 'It helps SEO',
#         href: '#'
#     }
# ]
